small util for key management
rustdesk/rustdesk-server pull request #62
Opened 2022-07-14 14:31 UTC by paspo

With this util, we add a way to generate and verify a keypair. The keypair generation is useful for first installation, especially when https://github.com/rustdesk/rustdesk-server/pull/61 gets approved.

The command will be something like:

```bash
docker run --rm --entrypoint /usr/bin/rustdesk-utils rustdesk/rustdesk-server:latest genkeypair
```

The expected output is something like this:

```text
Public Key:  e61C1tOULMqVbAf0kTlUbyBFNZ1eObXIOQ1O0BSSB/o=
Secret Key:  ZuDfy4g9/HO1U6003hTQSaFQNBT7XPpz4B4F2TOw9Uh7rULW05QsypVsB/SROVRvIEU1nV45tcg5DU7QFJIH+g==
```

The other available command is `validatekeypair` which is used to check if the keypair is valid:

```bash
rustdesk-utils validatekeypair 'e61C1tOULMqVbAf0kTlUbyBFNZ1eObXIOQ1O0BSSB/o=' 'ZuDfy4g9/HO1U6003hTQSaFQNBT7XPpz4B4F2TOw9Uh7rULW05QsypVsB/SROVRvIEU1nV45tcg5DU7QFJIH+g=='
```

This will be used at the container startup to check keypair validity before program startup.

# NOTE

This is the first time i use rust. I really can use the help of a skilled developer to check on this work; that's why this is a draft.

2022-07-15 17:20 UTC, rustdesk commented
> a skilled developer

The goodness of of Rust is that a new developer can also write good code.

2022-07-15 17:30 UTC, rustdesk commented
And your Rust code seems not formatted, you can run `cargo fmt`

2022-07-21 02:52 UTC, rustdesk commented
@paspo have you seen my code review? I noticed some one can not see the in-code review.

![image](https://user-images.githubusercontent.com/71636191/180119756-4b6a1797-f0fa-43bb-9fed-d6cd56ec425b.png)

2022-07-21 03:34 UTC, rustdesk requested changes

2022-07-21 07:16 UTC, paspo commented on src/utils.rs
> +    println!("  validatekeypair [public key] [secret key]    Validate an existing keypair");
ok

2022-07-21 07:18 UTC, paspo commented on src/utils.rs
> +            process::exit(0x0001);
I read [here](https://docs.rs/failure/0.1.1/failure/macro.bail.html) that this macro is used for returning something from a function. Here I want the program to quit, with an exit status code to differentiate from a correct exit.

2022-07-21 07:19 UTC, paspo commented on src/utils.rs
> +    }
that's a lot better in readability

2022-07-21 07:23 UTC, rustdesk commented on src/utils.rs
> +            process::exit(0x0001);
You can quit from the calling function.

2022-07-21 08:43 UTC, paspo commented on src/utils.rs
> +            process::exit(0x0001);
ok.

Given this code:

```rust
use hbb_common::ResultType;

fn validate_keypair(pk: &str, sk: &str) -> ResultType<()>  {
    let sk1 = base64::decode(&sk);
    // ....
}
```

what is the "rust way" of saying "if decoding doesn't work, return with an error string"?
bonus points if you fit this in one line...

2022-07-21 09:11 UTC, merged